{% set name = "google-cloud-firestore" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/googleapis/python-firestore/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2137ba386cab06d103126d009acbbe720c38e71493b864ecee9d407fcb1c252d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - google-api-core-grpc >=1.32.0,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*
    - google-cloud-core >=1.4.1,<3.0.0dev
    - proto-plus >=1.22.0,<2.0.0dev
    - protobuf >=3.19.0,<5.0.0dev

test:
  imports:
    - google.cloud.firestore
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/googleapis/python-firestore
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python Client for Google Cloud Firestore
  doc_url: https://googleapis.dev/python/firestore/latest/index.html
  dev_url: https://github.com/googleapis/python-firestore

extra:
  recipe-maintainers:
    - xylar
    - mitchellsuter
