{% set name = "google-cloud-firestore" %}
{% set version = "2.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/googleapis/python-firestore/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 97b90c5cb7f68b4bdd298594b16de577fbab700a24f6e9771b5dec39a52507cf

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - google-api-core-grpc >=1.31.5,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0
    - google-cloud-core >=1.4.1,<3.0.0dev
    - proto-plus >=1.20.5,<2.0.0dev
    - protobuf >=3.19.0,<4.0.0dev"

test:
  imports:
    - google.cloud.firestore
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/googleapis/python-firestore
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python Client for Google Cloud Firestore
  doc_url: https://googleapis.dev/python/firestore/latest/index.html
  dev_url: https://github.com/googleapis/python-firestore

extra:
  recipe-maintainers:
    - xylar
    - mitchellsuter
